name: test types actions
on:
    push:
        branches:
            [main]

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Usando la de Composición
      - name: Use Composite Action
        uses: ./.github/actions/setup-and-clean

      # 2. Usando la de JavaScript
      - name: Use JS Action
        uses: ./.github/actions/hello-world-js
        with:
          who-to-greet: 'Odon'

      # 3. Usando la de Docker
      - name: Use Docker Action
        uses: ./.github/actions/docker-tool